# Generated by Django 5.1.6 on 2025-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_order_device_delete_orders_delete_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='counter_no',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
