# Generated by Django 5.1.6 on 2025-03-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_order_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
