# Generated by Django 5.1.6 on 2025-03-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_order_counter_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='counter_no',
            field=models.IntegerField(default=1),
        ),
    ]
