# Generated by Django 5.1.6 on 2025-03-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_device_created_at_device_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vendors.device'),
            preserve_default=False,
        ),
    ]
