# Generated by Django 5.1.6 on 2025-03-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_order_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vendors.device'),
        ),
    ]
